# below paper config
baseURL = 'https://www.bk201sama.eu.org/'
languageCode = 'zh-cn'
title = 'bk201的博客'
theme = "paper"

disqusShortname = 'bk201sama'   # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  # twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'bk201sama'                 # github.com/YOUR_GITHUB_ID
  # instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

  # home page profile
  # avatar = 'https://www.bk201sama.eu.org/img/avatar.jpg'                 # gravatar email or image url
  name = 'bk201'
  bio = '静静的听雨声，激烈的敲打键盘'

  # misc
  #disableHLJS = true                        # disable highlight.js
  #monoDarkIcon = true                       # show monochrome dark mode icon
  #gravatarCdn = 'https://cdn.v2ex.com/gravatar/'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  #graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)